# Generated by Django 3.2.20 on 2024-02-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('photo', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('gst_certificate', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('udhyam_certificate', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('cancelled_check', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('pan_card', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('aadhar_card', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
    ]
