# Generated by Django 3.2.20 on 2024-03-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banner',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='seller',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
