# Generated by Django 3.2.20 on 2024-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20240301_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='follower',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
