# Generated by Django 3.2.20 on 2024-03-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20240301_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='brand_slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
