# Generated by Django 3.2.20 on 2024-03-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20240301_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('aadhar', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('pan', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('cancelled_check', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('date', models.DateField(auto_now=True)),
                ('otp', models.IntegerField(blank=True, default=9241, null=True)),
                ('verification', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
            ],
        ),
    ]
