# Generated by Django 3.2.20 on 2024-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='aadhar',
            new_name='gst_certificate',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='cancelled_check',
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user_type',
            field=models.CharField(blank=True, default='Buyer', max_length=100, null=True),
        ),
    ]
