# Generated by Django 3.2.20 on 2024-03-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20240327_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('maincategory', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('maincategory_slug', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subcategory_slug', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('brand_slug', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('unit_slug', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('weight', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('minimum_purchase_qty', models.IntegerField()),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('product_thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('link_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('attribute', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('unit_price', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('discount_range', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('discount', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=1, null=True)),
                ('sku', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('external_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('external_link_button_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('key_features', models.TextField(blank=True, default='', null=True)),
                ('subcategory_specification', models.TextField(blank=True, default='', null=True)),
                ('product_description', models.TextField(blank=True, default='', null=True)),
                ('product_faq_title', models.TextField(blank=True, default='', null=True)),
                ('product_faq_answer', models.TextField(blank=True, default='', null=True)),
                ('pdf_specification', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('seo_meta_title', models.TextField(blank=True, default='', null=True)),
                ('meta_description', models.TextField(blank=True, default='', null=True)),
                ('meta_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('free_shipping', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fat_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_product_quality_multiply', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('low_stock_qty', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('hide_stock', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cash_on_delivery', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_day', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tax', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
