# Generated by Django 3.2.20 on 2024-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_brand_category_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
