# Generated by Django 3.2.20 on 2024-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20240328_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maincategory_slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
